ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
      - id: end-of-file-fixer
        exclude: 'setup.cfg'
      - id: trailing-whitespace
        exclude: 'setup.cfg'
      - id: debug-statements
      - id: check-yaml
      - id: check-case-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.34.0'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-pyupgrade
        args:
          - --py36-plus
      - id: nbqa-isort
      - id: nbqa-yapf
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        args:
          # Strip metadata but keep counts and outputs
          - --keep-count
          - --keep-output
  - repo: https://github.com/bdice/nb-strip-paths
    rev: v0.1.0
    hooks:
      - id: nb-strip-paths
