trigger: none

pr:
  - v3-api

schedules:
- cron: "0 2 * * *"
  displayName: Daily 10PM build
  # 2am UTC is 10PM eastern time
  branches:
    include:
    - "*"

variables:
- template: variables/image.yml

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.1.0

jobs:
- template: job--pre-commit.yml@asottile
- template: jobs/execute_notebooks.yml
  parameters:
      build_master: true
