parameters:
- name: build_master
  displayName: 'Build HOOMD master branch?'
  type: boolean
  default: false

jobs:
- job: notebooks
  displayName: Execute notebooks
  timeoutInMinutes: 360

  pool:
    vmImage: 'ubuntu-latest'

  container:
      image: $(image_root)-nompi
      options: -u 0

  workspace:
    clean: all

  steps:
  - ${{ if eq(parameters.build_master, true) }}:
    - template: steps/build_hoomd.yml
  - script: jupyter nbconvert --execute --inplace **/*.ipynb
    displayName: Execute notebooks
    workingDirectory: $(Build.SourcesDirectory)
    env:
      PYTHONPATH: $(Pipeline.Workspace)/hoomd/build;$(Pipeline.Workspace)/fresnel/build
